### ISSUE TITLE
데모 페이지와 해당 소스와는 다른 것 같습니다!

### ISSUE THREAD

**Issue by kangorange** [chanwooo/SE17_Approval#2]
메일(Chanwookim@me.com)로 보내드린바와 같이 데모 페이지와 해당 소스와는 다른 것 같습니다 ㅠ

데모 페이지와 같은 풀 소스 요청드립니다!

**Comment by chanwooo** [comment]
관심을 가져주셔서 감사합니다 🙇
데모서버에 올라가있는 소스코드를 업로드 해놨습니다. 해당이슈는 닫도록 하겠습니다.
